spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true
server.port=${PORT:8080}

cloudinary.cloud_name=dyvec4jx4
cloudinary.api_key=241176949895529
cloudinary.api_secret=CTOO6iqB4-VJhXiZlqWhHYoP4Is


