spring.data.mongodb.uri=mongodb://localhost:27017/catalogo
spring.data.mongodb.auto-index-creation=true
server.port=${PORT:8080}

cloudinary.cloud_name=dyvec4jx4
cloudinary.api_key=241176949895529
cloudinary.api_secret=CTOO6iqB4-VJhXiZlqWhHYoP4Is

<maven.compiler.source>17</maven.compiler.source>
<maven.compiler.target>17</maven.compiler.target>
